---
- hosts: calc-stage
  become: yes
  tasks:
    - name: install Redis
      apt:
        name: redis-server
        state: present
    - name: start Redis
      service:
        name: redis-server
        state: started
    - name: copy Redis configuration
      copy:
        src: redis.conf
        dest: /etc/redis/redis.conf
      notify: restart Redis
  handlers:
    - name: restart Redis
      service:
        name: redis-server
        state: restarted

- hosts: calc-stage
  become: yes
  tasks:
    - name: ensure Java Runtime Environment is installed
      apt:
        name: default-jre
        state: present
    - name: create directory for Calculator
      file:
        path: /var/calculator
        state: directory
    - name: configure Calculator as a service
      file:
        path: /etc/init.d/calculator
        state: link
        force: yes
        src: /var/calculator/calculator.jar
    - name: copy Calculator
      copy:
        src: build/libs/calculator-0.0.1-SNAPSHOT.jar
        dest: /var/calculator/calculator.jar
        mode: a+x
      notify:
      - restart Calculator
  handlers:
    - name: restart Calculator
      service:
        name: calculator
        enabled: yes
        state: restarted